"""Skill ↔ tutorial-notebook index for omicverse-skills.

The shipped ``notebook_index.json`` records which omicverse-tutorials
notebook(s) each skill covers, along with each notebook's md5,
filesystem mtime, and last-touching git commit. When the upstream
tutorials repo updates a notebook, ``check_freshness`` flags the
skills whose recorded fingerprints have drifted, so the skill can be
re-reviewed.

Public API
----------
- :data:`SKILL_NOTEBOOK_MAP` — the canonical skill → list-of-notebook-
  basenames mapping. Edit here when you add a new skill.
- :func:`load_index` — read ``notebook_index.json`` shipped inside the
  package; returns the parsed dict.
- :func:`build_index` — re-compute md5 / mtime / git info for every
  skill in :data:`SKILL_NOTEBOOK_MAP` against a given
  ``omicverse-tutorials`` checkout and write a fresh JSON.
- :func:`check_freshness` — compare current notebook fingerprints
  against the shipped JSON; return a list of stale entries.
- :func:`format_freshness_report` — human-readable rendering of
  :func:`check_freshness` output.

CLI
---
``python -m omicverse_skills.notebook_index build --tutorials <path>``
``python -m omicverse_skills.notebook_index check  --tutorials <path>``
``python -m omicverse_skills.notebook_index show   [skill-name]``
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Mapping, Optional


__all__ = [
    "SKILL_NOTEBOOK_MAP",
    "TUTORIALS_REPO_URL",
    "TUTORIALS_REPO_URL_LEGACY",
    "INDEX_FILENAME",
    "load_index",
    "index_path",
    "build_index",
    "check_freshness",
    "format_freshness_report",
    "FreshnessEntry",
]


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TUTORIALS_REPO_URL        = "https://github.com/omicverse/omicverse-tutorials"
TUTORIALS_REPO_URL_LEGACY = "https://github.com/Starlitnightly/omicverse-tutorials"

INDEX_FILENAME = "notebook_index.json"

#: Tutorial directories under ``omicverse-tutorials/docs`` that we walk for
#: source notebooks (everything else under ``docs/`` is auto-generated by
#: Sphinx and lives under ``_build/`` — we ignore those).
TUTORIAL_DIRS = (
    "Tutorials-bulk", "Tutorials-llm", "Tutorials-metabol",
    "Tutorials-microbiome", "Tutorials-Multi-Omics", "Tutorials-plotting",
    "Tutorials-single", "Tutorials-space", "Tutorials-velo",
)


# ---------------------------------------------------------------------------
# The canonical skill → notebook-basename map.
# Keys are skill directory names under ``src/omicverse_skills/skills/``.
# Values are notebook basenames (with ``.ipynb``) found anywhere under
# ``omicverse-tutorials/docs/Tutorials-*/``. Empty list = utility-only
# skill with no canonical tutorial.
# ---------------------------------------------------------------------------

SKILL_NOTEBOOK_MAP: Mapping[str, list[str]] = {
    # ------------------------------------------------------------------
    # Utility skills with no canonical tutorial
    # ------------------------------------------------------------------
    "biocontext-knowledge":           [],
    "data-export-excel":              [],
    "data-export-pdf":                [],
    "data-io-loading":                [],
    "data-stats-analysis":            [],
    "data-transform":                 [],
    "data-viz-plots":                 [],
    "datasets-loading":               [],
    "gsea-enrichment":                [],
    "single-cell-differential-abundance":   [],
    "single-cell-lda-topic-clustering":     [],
    "single-popv-annotation":               [],

    # ------------------------------------------------------------------
    # Bulk RNA-seq
    # ------------------------------------------------------------------
    "bulk-celltype-deconvolution":          ["t_decov_bulk.ipynb"],
    "bulk-combat-correction":               ["t_bulk_combat.ipynb"],
    "bulk-deg-analysis":                    ["t_deg.ipynb"],
    "bulk-deseq2-analysis":                 ["t_deseq2.ipynb"],
    "bulk-stringdb-ppi":                    ["t_network.ipynb"],
    "bulk-to-single-deconvolution":         ["t_bulk2single.ipynb"],
    "bulk-trajblend-interpolation":         ["t_bulktrajblend.ipynb"],
    "bulk-wgcna-analysis":                  ["t_wgcna.ipynb"],
    "fastq-analysis":                       ["t_mapping_STAR.ipynb",
                                              "t_mapping_kbpython.ipynb"],
    "tcga-preprocessing":                   ["t_tcga.ipynb"],

    # ------------------------------------------------------------------
    # Bulk metabolomics (4 skills, 11 notebooks)
    # ------------------------------------------------------------------
    "bulk-metabol-preprocessing": [
        "t_metabol_01_intro.ipynb",
        "t_metabol_06_batch_correction.ipynb",
    ],
    "bulk-metabol-multivariate": [
        "t_metabol_02_multivariate.ipynb",
        "t_metabol_08_biomarker.ipynb",
    ],
    "bulk-metabol-untargeted-lipidomics": [
        "t_metabol_04_untargeted.ipynb",
        "t_metabol_05_lipidomics.ipynb",
    ],
    "bulk-metabol-pathway-multifactor": [
        "t_metabol_03_pathway.ipynb",
        "t_metabol_07_multifactor.ipynb",
        "t_metabol_09_dgca.ipynb",
        "t_metabol_10_multiomics.ipynb",
        "t_metabol_11_real_data_mtbls1.ipynb",
    ],

    # ------------------------------------------------------------------
    # Microbiome (5 skills + paired)
    # ------------------------------------------------------------------
    "microbiome-16s-amplicon-dada2": [
        "t_16s_amplicon.ipynb",
        "t_16s_dada2.ipynb",
    ],
    "microbiome-da-comparison":             ["t_16s_da_comparison.ipynb"],
    "microbiome-meta-analysis":             ["t_16s_meta_analysis.ipynb"],
    "microbiome-phylogeny":                 ["t_16s_phylogeny.ipynb"],
    "micro-metabol-paired":                 ["t_micro_metabol_paired.ipynb"],

    # ------------------------------------------------------------------
    # Single-cell — preprocessing / annotation / DE / clustering
    # ------------------------------------------------------------------
    "single-cell-preprocessing": [
        "t_preprocess.ipynb",
        "t_preprocess_cpu.ipynb",
        "t_preprocess_gpu.ipynb",
        "t_preprocess_rust.ipynb",
    ],
    "single-cell-annotation": [
        "t_cellanno.ipynb",
        "t_anno_noref.ipynb",
        "t_gptanno.ipynb",
    ],
    "reference-label-transfer":             ["t_anno_ref.ipynb"],
    "cross-modal-celltype-transfer":        ["t_anno_trans.ipynb"],
    "single-cell-cellmatch-ontology":       ["t_cellmatch.ipynb"],
    "single-cell-cellvote-consensus":       ["t_cellvote_pbmc3k.ipynb"],
    "single-cell-metatime-annotation":      ["t_metatime.ipynb"],
    "single-cell-batch-integration":        ["t_single_batch.ipynb"],
    "single-cell-clustering-backends":      ["t_cluster.ipynb"],
    "single-cell-cnmf-program-discovery":   ["t_cnmf.ipynb"],
    "single-cell-differential-expression": [
        "t_scdeg.ipynb", "t_deg_single.ipynb",
    ],
    "single-cell-kb-alignment": [
        "t_alignment_1k.ipynb", "t_alignment_velocity.ipynb",
    ],

    # ------------------------------------------------------------------
    # Single-cell — trajectory / velocity / fate
    # ------------------------------------------------------------------
    "single-cell-trajectory-inference": [
        "t_traj_diffusion.ipynb",
        "t_traj_palantir.ipynb",
        "t_traj_slingshot.ipynb",
    ],
    "single-cell-monocle2-trajectory":      ["t_traj_monocle2_olsson.ipynb"],
    "single-cell-via-trajectory":           ["t_via.ipynb",
                                              "t_via_velo.ipynb"],
    "single-cell-sctour-trajectory":        ["t_traj_sctour.ipynb"],
    "single-cell-rna-velocity":             ["t_velo.ipynb",
                                              "t_graphvelo.ipynb"],
    "single-cell-cellrank-fate":            ["t_velo_cellrank.ipynb"],

    # ------------------------------------------------------------------
    # Single-cell — communication / cellfate / downstream
    # ------------------------------------------------------------------
    "single-cell-cellphonedb-communication": ["t_ccc_cellphonedb.ipynb"],
    "single-cell-liana-communication":       ["t_ccc_liana.ipynb"],
    "single-cellfate-analysis": [
        "t_cellfate.ipynb",
        "t_cellfate_gene.ipynb",
        "t_cellfate_genesets.ipynb",
    ],
    "single-cell-scenic":                   ["t_scenic.ipynb"],
    "single-cell-cytotrace2":               ["t_cytotrace.ipynb"],
    "single-downstream-analysis": [
        "t_aucell.ipynb",
        "t_metacells.ipynb",
        "t_lazy.ipynb",
        "t_scdrug.ipynb",
        "t_nocd.ipynb",
    ],
    "single-multiomics": [
        "t_mofa.ipynb",
        "t_mofa_glue.ipynb",
        "t_simba.ipynb",
        "t_tosica.ipynb",
        "t_stavia.ipynb",
    ],
    "single-to-spatial-mapping":            ["t_single2spatial.ipynb"],

    # ------------------------------------------------------------------
    # Foundation models
    # ------------------------------------------------------------------
    "fm-foundation-models": sorted({
        "t_cellplm.ipynb", "t_dr.ipynb",
        "t_fm.ipynb",
        "t_fm_aidocell.ipynb", "t_fm_atacformer.ipynb",
        "t_fm_cell2sentence.ipynb", "t_fm_cellfm.ipynb",
        "t_fm_chatcell.ipynb", "t_fm_genecompass.ipynb",
        "t_fm_genept.ipynb", "t_fm_langcell.ipynb",
        "t_fm_nicheformer.ipynb", "t_fm_pulsar.ipynb",
        "t_fm_scbert.ipynb", "t_fm_sccello.ipynb",
        "t_fm_scmulan.ipynb", "t_fm_scplantllm.ipynb",
        "t_fm_scprint.ipynb", "t_fm_tabula.ipynb",
        "t_fm_tgpt.ipynb",
        "t_geneformer.ipynb", "t_scfoundation.ipynb",
        "t_scgpt.ipynb", "t_scmulan.ipynb",
        "t_uce.ipynb",
    }),

    # ------------------------------------------------------------------
    # Spatial transcriptomics
    # ------------------------------------------------------------------
    "spatial-tutorials": sorted([
        # Tutorials-space/*.ipynb
        "t_cellpose.ipynb", "t_cluster_space.ipynb",
        "t_commot_flowsig.ipynb", "t_crop_rotate.ipynb",
        "t_decov.ipynb", "t_flashdeconv.ipynb",
        "t_gaston.ipynb", "t_mapping.ipynb",
        "t_nanostring_preprocess.ipynb",
        "t_slat.ipynb", "t_spaceflow.ipynb",
        "t_stagate.ipynb", "t_staligner.ipynb",
        "t_starfysh.ipynb", "t_starfysh_new.ipynb",
        "t_stt.ipynb", "t_visium_hd_preprocess.ipynb",
        "t_xenium_preprocess.ipynb",
        # Tutorials-space/cluster/*.ipynb (spatial-clustering benchmarks)
        "t_cluster_banksy.ipynb", "t_cluster_binary.ipynb",
        "t_cluster_cast.ipynb", "t_cluster_graphst.ipynb",
        "t_cluster_stagate.ipynb",
    ]),

    # ------------------------------------------------------------------
    # Plotting / visualisation
    # ------------------------------------------------------------------
    "plotting-visualization": [
        "t_palette.ipynb",
        "t_plot1cell.ipynb",
        "t_publication_plotting.ipynb",
        "t_visualize_bulk.ipynb",
        "t_visualize_colorsystem.ipynb",
        "t_visualize_single.ipynb",
    ],
}


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

def index_path() -> Path:
    """Return the absolute path to the shipped ``notebook_index.json``."""
    return Path(__file__).resolve().parent / INDEX_FILENAME


def load_index(path: Optional[os.PathLike] = None) -> dict:
    """Read the shipped notebook index. Override ``path`` for a custom file."""
    p = Path(path) if path is not None else index_path()
    return json.loads(p.read_text(encoding="utf-8"))


def md5_of(path: Path) -> str:
    """Hex-encoded MD5 of the file at ``path``. Reads in 64 KiB chunks so
    even multi-MB notebooks don't materialise in memory."""
    h = hashlib.md5()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def fs_mtime_iso(path: Path) -> str:
    """ISO-8601 UTC mtime of ``path`` (seconds resolution)."""
    ts = path.stat().st_mtime
    return (_dt.datetime
            .fromtimestamp(ts, tz=_dt.timezone.utc)
            .isoformat(timespec="seconds"))


def _git_run(repo: Path, args: list[str]) -> str:
    """Run ``git -C repo args``; return stripped stdout, or '' on failure."""
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo), *args],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return ""


def git_last_commit(tutorials_repo: Path, rel_path: str) -> dict[str, str]:
    """Return ``{sha, date_iso}`` for the last commit that touched
    ``rel_path`` inside ``tutorials_repo``."""
    out = _git_run(tutorials_repo,
                   ["log", "-1", "--format=%H\t%cI", "--", rel_path])
    if not out or "\t" not in out:
        return {"sha": "", "date_iso": ""}
    sha, date_iso = out.split("\t", 1)
    return {"sha": sha, "date_iso": date_iso}


def git_repo_head(tutorials_repo: Path) -> dict[str, str]:
    sha       = _git_run(tutorials_repo, ["rev-parse", "HEAD"])
    date_iso  = _git_run(tutorials_repo, ["log", "-1", "--format=%cI"])
    return {"sha": sha, "date_iso": date_iso}


def _basename_to_relpath(tutorials_repo: Path) -> dict[str, str]:
    """For every notebook found under ``tutorials_repo/docs/Tutorials-*/``,
    map its basename ``"t_foo.ipynb"`` → relative POSIX path
    ``"docs/Tutorials-X/t_foo.ipynb"``. Notebooks under
    ``.ipynb_checkpoints`` or ``_build`` are ignored."""
    out: dict[str, str] = {}
    docs = tutorials_repo / "docs"
    for d in TUTORIAL_DIRS:
        sub = docs / d
        if not sub.exists():
            continue
        for nb in sub.rglob("t_*.ipynb"):
            if any(part in (".ipynb_checkpoints", "_build") for part in nb.parts):
                continue
            out[nb.name] = nb.relative_to(tutorials_repo).as_posix()
    return out


# ---------------------------------------------------------------------------
# Build / check
# ---------------------------------------------------------------------------

def build_index(
    tutorials_repo: os.PathLike,
    out_path: Optional[os.PathLike] = None,
    skill_map: Optional[Mapping[str, list[str]]] = None,
) -> dict:
    """Compute md5 / mtime / git info for every skill's notebooks and
    write a fresh JSON.

    Parameters
    ----------
    tutorials_repo : path
        Filesystem path to a checkout of the omicverse-tutorials repo
        (the directory containing ``docs/Tutorials-*/``).
    out_path : path, optional
        Where to write the JSON. Defaults to the in-package
        ``notebook_index.json``.
    skill_map : dict, optional
        Override the canonical mapping (defaults to
        :data:`SKILL_NOTEBOOK_MAP`).

    Returns
    -------
    dict
        The serialised index (also written to ``out_path``).
    """
    repo = Path(tutorials_repo).expanduser().resolve()
    if not (repo / "docs").exists():
        raise FileNotFoundError(
            f"omicverse-tutorials repo not found at {repo} (no docs/ subdir)"
        )
    skill_map = dict(skill_map if skill_map is not None else SKILL_NOTEBOOK_MAP)

    base_to_rel = _basename_to_relpath(repo)
    head        = git_repo_head(repo)

    skills_out: dict[str, dict] = {}
    for sk_name in sorted(skill_map):
        records: list[dict] = []
        unresolved: list[str] = []
        for base in skill_map[sk_name]:
            rel = base_to_rel.get(base)
            if rel is None:
                unresolved.append(base)
                continue
            nb_full = repo / rel
            git_info = git_last_commit(repo, rel)
            records.append({
                # `path` is recorded WITHOUT the .ipynb suffix so it matches
                # the canonical readthedocs URL stem; the .ipynb is implied.
                "path":                rel.removesuffix(".ipynb"),
                "md5":                 md5_of(nb_full),
                "fs_mtime_utc":        fs_mtime_iso(nb_full),
                "git_last_commit":     git_info["sha"],
                "git_last_commit_utc": git_info["date_iso"],
            })
        entry: dict = {"notebooks": records}
        if unresolved:
            entry["unresolved_basenames"] = unresolved
        skills_out[sk_name] = entry

    referenced = {nb["path"] for v in skills_out.values()
                  for nb in v["notebooks"]}
    all_basenames = set(base_to_rel)
    nbs_unref = sorted(
        b.removesuffix(".ipynb")
        for b in (all_basenames - {Path(p).name + ".ipynb" for p in referenced})
    )
    n_total_entries = sum(len(v["notebooks"]) for v in skills_out.values())

    out = {
        "version":  1,
        "tutorials_repo": {
            "url":              TUTORIALS_REPO_URL,
            "url_legacy":       TUTORIALS_REPO_URL_LEGACY,
            "git_commit":       head["sha"],
            "git_commit_utc":   head["date_iso"],
        },
        "checked_at_utc": _dt.datetime.now(tz=_dt.timezone.utc)
                              .isoformat(timespec="seconds"),
        "summary": {
            "n_skills":            len(skills_out),
            "n_skills_with_nb":    sum(1 for v in skills_out.values()
                                       if v["notebooks"]),
            "n_skills_no_nb":      sum(1 for v in skills_out.values()
                                       if not v["notebooks"]),
            "n_notebook_entries":  n_total_entries,
            "n_distinct_notebooks_referenced": len(referenced),
            "n_notebooks_in_repo": len(all_basenames),
            "n_notebooks_unreferenced_by_any_skill": len(nbs_unref),
            "notebooks_unreferenced_by_any_skill":   nbs_unref,
        },
        "skills": skills_out,
    }
    target = Path(out_path) if out_path is not None else index_path()
    target.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n",
                      encoding="utf-8")
    return out


@dataclass
class FreshnessEntry:
    """One drift record produced by :func:`check_freshness`."""

    skill:           str
    notebook_path:   str            # without .ipynb suffix
    status:          str            # 'changed' | 'missing' | 'unresolved'
    recorded_md5:    str = ""
    current_md5:     str = ""
    recorded_mtime:  str = ""
    current_mtime:   str = ""
    recorded_commit: str = ""
    current_commit:  str = ""

    def to_dict(self) -> dict:
        return {k: v for k, v in self.__dict__.items() if v != ""}


def check_freshness(
    tutorials_repo: os.PathLike,
    index: Optional[dict] = None,
    *,
    use_git: bool = True,
) -> List[FreshnessEntry]:
    """Compare the shipped JSON against a current omicverse-tutorials
    checkout. Returns a list of skills/notebooks whose fingerprint has
    drifted (md5 changed, file missing, etc.).

    Parameters
    ----------
    tutorials_repo : path
        Path to a checkout of omicverse-tutorials.
    index : dict, optional
        A pre-loaded index dict; if ``None``, loads from the shipped
        ``notebook_index.json``.
    use_git : bool, default True
        If False, skips the per-file ``git log -1`` lookup (faster).

    Returns
    -------
    list of FreshnessEntry
        Empty list ⇒ everything is in sync.
    """
    repo = Path(tutorials_repo).expanduser().resolve()
    idx = index if index is not None else load_index()
    drift: List[FreshnessEntry] = []

    for skill, info in idx.get("skills", {}).items():
        for nb in info.get("notebooks", []):
            nb_rel = nb["path"] + ".ipynb"
            nb_full = repo / nb_rel
            if not nb_full.exists():
                drift.append(FreshnessEntry(
                    skill=skill, notebook_path=nb["path"],
                    status="missing",
                    recorded_md5=nb.get("md5", ""),
                ))
                continue
            cur_md5 = md5_of(nb_full)
            if cur_md5 != nb.get("md5"):
                e = FreshnessEntry(
                    skill=skill, notebook_path=nb["path"],
                    status="changed",
                    recorded_md5=nb.get("md5", ""),
                    current_md5=cur_md5,
                    recorded_mtime=nb.get("fs_mtime_utc", ""),
                    current_mtime=fs_mtime_iso(nb_full),
                )
                if use_git:
                    cur = git_last_commit(repo, nb_rel)
                    e.recorded_commit = nb.get("git_last_commit", "")
                    e.current_commit  = cur["sha"]
                drift.append(e)
        for base in info.get("unresolved_basenames", []) or []:
            drift.append(FreshnessEntry(
                skill=skill, notebook_path=base,
                status="unresolved",
            ))

    return drift


def format_freshness_report(stale: Iterable[FreshnessEntry]) -> str:
    """Pretty-print :func:`check_freshness` output for a terminal."""
    lines: list[str] = []
    by_status: dict[str, list[FreshnessEntry]] = {}
    for e in stale:
        by_status.setdefault(e.status, []).append(e)

    for status in ("changed", "missing", "unresolved"):
        items = by_status.get(status, [])
        if not items:
            continue
        lines.append(f"=== {status.upper()} ({len(items)}) ===")
        for e in items:
            lines.append(f"  [{e.skill}]  {e.notebook_path}")
            if status == "changed":
                lines.append(f"      recorded md5: {e.recorded_md5}")
                lines.append(f"      current  md5: {e.current_md5}")
                if e.recorded_commit and e.current_commit:
                    lines.append(f"      recorded commit: {e.recorded_commit[:12]}")
                    lines.append(f"      current  commit: {e.current_commit[:12]}")
        lines.append("")

    if not lines:
        return "All notebooks match the shipped index. ✓"
    return "\n".join(lines).rstrip()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _resolve_tutorials_arg(arg: Optional[str]) -> Path:
    """Pick a sensible default for the tutorials repo path."""
    if arg:
        p = Path(arg).expanduser().resolve()
        if not p.exists():
            raise SystemExit(f"--tutorials path does not exist: {p}")
        return p
    env = os.environ.get("OMICVERSE_TUTORIALS_REPO")
    if env:
        p = Path(env).expanduser().resolve()
        if p.exists():
            return p
    raise SystemExit(
        "Specify the tutorials repo via --tutorials <path> "
        "or the OMICVERSE_TUTORIALS_REPO env var.\n"
        f"Canonical URL: {TUTORIALS_REPO_URL}"
    )


def _cli() -> None:
    p = argparse.ArgumentParser(
        prog="python -m omicverse_skills.notebook_index",
        description="Skill ↔ tutorial-notebook index management.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    p_build = sub.add_parser("build", help="Recompute the index from a tutorials checkout")
    p_build.add_argument("--tutorials", help="Path to omicverse-tutorials checkout")
    p_build.add_argument("--out",       help="Where to write the JSON (default: in-package)")

    p_check = sub.add_parser("check", help="Check freshness of the shipped index")
    p_check.add_argument("--tutorials", help="Path to omicverse-tutorials checkout")
    p_check.add_argument("--no-git",    action="store_true", help="Skip per-file git log lookup")
    p_check.add_argument("--json",      action="store_true", help="Emit machine-readable JSON")

    p_show = sub.add_parser("show", help="Print the shipped index for a skill (or all)")
    p_show.add_argument("skill", nargs="?", help="Skill name; omit for full index")

    args = p.parse_args()

    if args.cmd == "build":
        repo = _resolve_tutorials_arg(args.tutorials)
        out  = build_index(repo, args.out)
        s = out["summary"]
        print(f"Wrote {args.out or index_path()}")
        for k in ("n_skills", "n_skills_with_nb", "n_skills_no_nb",
                  "n_notebook_entries", "n_distinct_notebooks_referenced",
                  "n_notebooks_in_repo", "n_notebooks_unreferenced_by_any_skill"):
            print(f"  {k}: {s[k]}")
        return

    if args.cmd == "check":
        repo = _resolve_tutorials_arg(args.tutorials)
        stale = check_freshness(repo, use_git=not args.no_git)
        if args.json:
            print(json.dumps([e.to_dict() for e in stale], indent=2,
                              ensure_ascii=False))
        else:
            print(format_freshness_report(stale))
        sys.exit(1 if stale else 0)

    if args.cmd == "show":
        idx = load_index()
        if args.skill is None:
            print(json.dumps(idx, indent=2, ensure_ascii=False))
            return
        if args.skill not in idx.get("skills", {}):
            raise SystemExit(f"Unknown skill: {args.skill}")
        print(json.dumps(idx["skills"][args.skill], indent=2,
                          ensure_ascii=False))
        return


if __name__ == "__main__":   # pragma: no cover
    _cli()
